### PR TITLE
Emergency android test fix

### LINKED ISSUE #345: Quick fix UI tests
- A commit broke the tests

### PR DESCRIPTION
**Pull request by ElMaestroZ**
This pull request includes several changes to the Android instrumented tests in the `shelfLife` project. This fixes issues created by an unfortunate series of PRs.

### Fix
* We changed a few things in the test architecture that broke a few of the android tests.

### Code Readability Improvements:

* Simplified the instantiation of `SignInViewModel` and the `SignInScreen` setup in `SignInScreenTest.kt` by reducing indentation and line breaks. [[1]](diffhunk://#diff-f28c3614feb41675c3d4686cd0afe8d6a710d33c082015c2e9d66908d06f52b3L53-R65) [[2]](diffhunk://#diff-f28c3614feb41675c3d4686cd0afe8d6a710d33c082015c2e9d66908d06f52b3L86-R85) [[3]](diffhunk://#diff-f28c3614feb41675c3d4686cd0afe8d6a710d33c082015c2e9d66908d06f52b3L107-R97) [[4]](diffhunk://#diff-f28c3614feb41675c3d4686cd0afe8d6a710d33c082015c2e9d66908d06f52b3L128-R115) [[5]](diffhunk://#diff-f28c3614feb41675c3d4686cd0afe8d6a710d33c082015c2e9d66908d06f52b3L155-R139)

### Dependency Additions:

* Added `PermissionRepository` and `PermissionRepositoryTestHelper` dependencies to `BarcodeScannerScreenTest.kt` to handle permission-related tests. [[1]](diffhunk://#diff-1f060d22cfcaa07b4fe5e32667c8493e951e2014a906e9be75f6e886ad762d9fR7-R13) [[2]](diffhunk://#diff-1f060d22cfcaa07b4fe5e32667c8493e951e2014a906e9be75f6e886ad762d9fR32-R34) [[3]](diffhunk://#diff-1f060d22cfcaa07b4fe5e32667c8493e951e2014a906e9be75f6e886ad762d9fR48-R65)
* Added `HouseHoldRepository` and corresponding test helpers to `InvitationScreenTest.kt` to manage household-related tests. [[1]](diffhunk://#diff-79aab7c0d83f5d408b61ee42fc345d9ae474d2faa2f68cca509ee700d1bede6cR11) [[2]](diffhunk://#diff-79aab7c0d83f5d408b61ee42fc345d9ae474d2faa2f68cca509ee700d1bede6cR21-L23) [[3]](diffhunk://#diff-79aab7c0d83f5d408b61ee42fc345d9ae474d2faa2f68cca509ee700d1bede6cR40-R53) [[4]](diffhunk://#diff-79aab7c0d83f5d408b61ee42fc345d9ae474d2faa2f68cca509ee700d1bede6cL62-R65) [[5]](diffhunk://#diff-79aab7c0d83f5d408b61ee42fc345d9ae474d2faa2f68cca509ee700d1bede6cL73-R81)
* Added `HouseholdRepositoryTestHelper` and `UserRepositoryTestHelper` to `LeaderboardScreenTest.kt` for better test data management. [[1]](diffhunk://#diff-00174d7ef4104b0fec55ad2dc67bf0aa8e77f060e31dde094f02758e041bfb8fL5-L18) [[2]](diffhunk://#diff-00174d7ef4104b0fec55ad2dc67bf0aa8e77f060e31dde094f02758e041bfb8fR33-R35)

### Test Helper Utilization:

* Replaced direct manipulation of flows with test helpers in `InvitationScreenTest.kt` to improve test setup and readability. [[1]](diffhunk://#diff-79aab7c0d83f5d408b61ee42fc345d9ae474d2faa2f68cca509ee700d1bede6cL62-R65) [[2]](diffhunk://#diff-79aab7c0d83f5d408b61ee42fc345d9ae474d2faa2f68cca509ee700d1bede6cL73-R81) [[3]](diffhunk://#diff-79aab7c0d83f5d408b61ee42fc345d9ae474d2faa2f68cca509ee700d1bede6cL108-R110) [[4]](diffhunk://#diff-79aab7c0d83f5d408b61ee42fc345d9ae474d2faa2f68cca509ee700d1bede6cL139-R141) [[5]](diffhunk://#diff-79aab7c0d83f5d408b61ee42fc345d9ae474d2faa2f68cca509ee700d1bede6cL172-R174) [[6]](diffhunk://#diff-79aab7c0d83f5d408b61ee42fc345d9ae474d2faa2f68cca509ee700d1bede6cL186-R188)
* Used `PermissionRepositoryTestHelper` in `BarcodeScannerScreenTest.kt` to simulate permission results. [[1]](diffhunk://#diff-1f060d22cfcaa07b4fe5e32667c8493e951e2014a906e9be75f6e886ad762d9fR48-R65) [[2]](diffhunk://#diff-1f060d22cfcaa07b4fe5e32667c8493e951e2014a906e9be75f6e886ad762d9fR89)

### Import Cleanups:

* Removed unused imports in several test files to keep the codebase clean and maintainable. [[1]](diffhunk://#diff-660da6487b1eabeda3ad633ffe2182486a3f6b222a27ec44d73c0a227ffedd3eL9-L11) [[2]](diffhunk://#diff-00174d7ef4104b0fec55ad2dc67bf0aa8e77f060e31dde094f02758e041bfb8fL5-L18)

These changes collectively enhance the readability, maintainability, and functionality of the instrumented tests in the project.

### CODE REVIEW

File: app/src/androidTest/java/com/android/shelfLife/ui/easteregg/EasterEggScreenTest.kt [hunk 1]
```diff
@@ -6,9 +6,7 @@ import androidx.compose.ui.test.onNodeWithTag
 import androidx.compose.ui.test.onNodeWithText
 import androidx.compose.ui.test.performClick
 import com.android.shelfLife.HiltTestActivity
-import com.android.shelfLife.R
```
Comment (alextheprophecy) [inline app/src/androidTest/java/com/android/shelfLife/ui/easteregg/EasterEggScreenTest.kt:9]: ## irrelevant modifications
- some of these changes are good for cleaning up the codebase, but they contribute to bloating the size of the PR
- It would have been nice to only focus on the Emergency fix, this file has nothing to do with it

File: app/src/androidTest/java/com/android/shelfLife/ui/camera/BarcodeScannerScreenTest.kt [hunk 2]
```diff
@@ -40,18 +45,24 @@ class BarcodeScannerScreenTest {
...
+
     // Mock repository flows
     whenever(foodFactsRepository.searchStatus).thenReturn(searchStatusFlow.asStateFlow())
     whenever(foodFactsRepository.foodFactsSuggestions)
         .thenReturn(foodFactsSuggestionsFlow.asStateFlow())
+
+    whenever(permissionRepository.onPermissionResult(any())).then {
+      permissionRepositoryTestHelper.setPermissionGranted(false)
+      permissionRepositoryTestHelper.setPermissionRequested(true)
+    }
```
Comment (alextheprophecy) [inline app/src/androidTest/java/com/android/shelfLife/ui/camera/BarcodeScannerScreenTest.kt:58]: ## Good job
- nice usage of the new permissionsRepository helper test class for testing.
> - I know this was a tricky part that we hadn't tested before M2

File: app/src/androidTest/java/com/android/shelfLife/ui/invitations/InvitationScreenTest.kt [hunk 3]
```diff
@@ -70,13 +72,13 @@ class InvitationScreenTest {
...
   private fun createViewModel(): InvitationViewModel {
     // Create the ViewModel after we set the userInvitationsFlow and mocks
-    return InvitationViewModel(invitationRepository, userRepository)
+    return InvitationViewModel(invitationRepository, userRepository, houseHoldRepository)
   }
 
   @Test
   fun noInvitationsDisplaysNoPendingMessage(): Unit = runBlocking {
     // No invitations scenario
-    userInvitationsFlow.value = emptyList()
```
Comment (alextheprophecy) [inline app/src/androidTest/java/com/android/shelfLife/ui/invitations/InvitationScreenTest.kt:79]: ## good job
-replacing the direct manipulation of state flows with the repository test helper instead

**Review by alextheprophecy — APPROVED** [review]
## PR size and scope
 - Maybe you could have only ran ktfmt on the relevant files, because this PR is **really** messy to go through
 - You also adress some cleaning up of the codebase which are not relevant commits to the "Emergency android fix" issue
- I scanned through the entire PR, and the actual modifications described in your PR were indeeed the only meaningful changes

## Overall
- Nice PR descirption links: the number links to the code sections in your PR comment are great to navigate through and actualy understand the code. 
- Good job on fixing the tests, it was indeed an emergency for the Ci to pass on main
- Good job using the `PermissinosRepositoryTestHelper`, you wrote cleaner and functional code
### Note
- This PR was really messy for me to look through, maybe next time avoid pushing all the files modified by ktfmt format, or make that a seperate PR, because it becomes very tricky to go through the code
