### PR TITLE
Fix/318 general clean up of the app

### LINKED ISSUE #318: General clean up of the app
Involves:
-Fixing the await thing in all the models to make it work offline
-fixing the string to long conversion in barcode scanner to avoid corner case where barcode is scanned wrong and the app crashes
-making it so only last person to delete a household truly deletes it, others only leave
-fixing permission denied screen UI

### PR DESCRIPTION
**Pull request by matvitn**
Fellow Crime Commiters, we are approaching the end and with it I took upon myself to do some general clean-up for our beautiful app:

This Clean-Up involves the following tasks:
-Fixing the await thing in all the models to make it work offline
-fixing the string to long conversion in barcode scanner to avoid corner case where barcode is scanned wrong and the app crashes
-making it so only last person to delete a household truly deletes it, others only leave
-fixing permission denied screen UI

Here is a breakdown of each task:

### Fixing the await thing in all the models to make it work offline
This was by far the most complicated task. It involved going to all the models that communicated with firebase and changing the try-catch structure we had to an asynchronous one that calls onSuccessListener and onFailureListener. This makes it so even if the thread is terminated when you leave the viewmodel, onSuccess and onFailure still execute based on the result of the db operation. 
Normally this task should've been ok. The main issue was that since we often had to update two sections of the firebase with two different calls at the same time (recipe and recipeUID list, Household and householdUID list, ...), I had to make it so that they stayed consistent (imagine if the first one fails and the second one succeeds). To do so I gave some of these functions callbacks and made it so only if the first one was successful, the second one would be called. That way making them consistent and ensuring that the user doesnt feel any disconnect.

### Fixing the string to long conversion in barcode scanner to avoid corner case where barcode is scanned wrong and the app crashes
This task was reasonably simple, all I had to do was call a function that checks if the string can be converted and if not returns a null. I then check for the null and if so, declare the search failed and display the error pop-up

### Making it so only last person to delete a household truly deletes it, others only leave
This one was also more complicated than I expected since the previous way of deleting a household was quite unclean and hard to adapt. This meant I had to redo the function so that it looks nicer and also fits the new firestore interactions that also take a callback. As it is, the only person that truly deletes the household and list of fooditems from the database is the last person to leave a household (so that we dont have many empty households occupying space in firebase). Any other case will make it so that only that user leaves the household while the others can still use it as normal

### Fixing permission denied screen UI
This one was also super easy, I simply had to center the text and add some padding to make it fit the screen nicely.

I know you're probably worried "Mateus why are you modifying the backend a few days before the deadline! wont this mess up the tests". The answer dear friend is "No". The backend still functions the exact same, despite me making most functions no longer be suspend, calling them from another thread is still possible and works fine (meaning the tests work the same even if the function is no longer suspend).

I hope you enjoy my improvements and please let me know if you need anything changed!!!

## UPDATE 18/12/2024

Since the PR was created there have been a few additions:

### Modify Model Tests so they fit with new asynchronous methods:
Oopsie! Turns out some tests did require modifying in order to work properly. This task took a really long time because some of the tests were very convoluted and didnt adapt well with asynchronous updated. This meant modifying them was actually much more complex than expected (with some of them I had to make completely new tests)

### Make Tests for DeletionConfirmationViewModel:
Since I made many modifications to this class (completely changed it). I found it prudent to also make tests for it to ensure it works properly

### Make Recipe Execution update the RatPoints if you steal someone else's food:
This involved going in the ExecuteRecipeViewModel and modifying it so that when you consume an item, it checks if its yours (by your user UID) and if not, adds the respective ratPoints to you for that household.

### Make Tests for ExecuteRecipeViewModel:
Since I modified the class and the tests still didnt exist I found it prudent to also make tests for it to ensure its functionality and increase overall coverage.

### CODE REVIEW

File: app/src/main/java/com/android/shelfLife/model/foodItem/FoodItemRepositoryFirestore.kt [hunk 1]
```diff
@@ -32,25 +32,24 @@ class FoodItemRepositoryFirestore @Inject constructor(private val db: FirebaseFi
...
-          .document(foodItem.uid)
-          .set(foodItem.toMap())
-    } catch (e: Exception) {
-      Log.e("FoodItemRepository", "Error adding food item", e)
-      val updatedFoodItems = _foodItems.value.filterNot { it.uid == foodItem.uid }
-      _foodItems.value = updatedFoodItems
-      // Notify the user about the error
-      _errorMessage.value = "Failed to add item. Please try again."
-    }
+  override fun addFoodItem(householdId: String, foodItem: FoodItem) {
```
Comment (AleMerRom) [inline app/src/main/java/com/android/shelfLife/model/foodItem/FoodItemRepositoryFirestore.kt:42]: we have had a conversation on why you do this in the following manner. 
Whit the await we used previously, the app would not work correctly during the offline mode. But we cannot just remove it. That is why you add these listeners. You do not add a addOnSuccessListener, because you have already updated the local cache optimistically. 

I really like it. Good work

File: app/src/main/java/com/android/shelfLife/model/foodItem/FoodItemRepositoryFirestore.kt [hunk 2]
```diff
@@ -118,76 +117,78 @@ class FoodItemRepositoryFirestore @Inject constructor(private val db: FirebaseFi
...
+    }
+    _foodItems.value = currentFoodItems
+
+    // Perform Firebase operation asynchronously
+    db.collection(collectionPath)
+        .document(householdId)
+        .collection("items")
+        .document(foodItem.uid)
+        .set(foodItem.toMap())
+        .addOnSuccessListener {
```
Comment (AleMerRom) [inline app/src/main/java/com/android/shelfLife/model/foodItem/FoodItemRepositoryFirestore.kt:155]: you have added a addOnSuccess for a Log. It is not necessary but it not a problem that it is there

File: app/src/main/java/com/android/shelfLife/model/household/HouseHoldRepository.kt [hunk 3]
```diff
@@ -29,13 +29,13 @@ interface HouseHoldRepository {
...
-  suspend fun addHousehold(household: HouseHold)
+  fun addHousehold(household: HouseHold)
 
   /** Updates an existing household in the repository. */
-  suspend fun updateHousehold(household: HouseHold)
+  fun updateHousehold(household: HouseHold, function: (String) -> Unit = {})
 
   /** Deletes a household by its unique ID. */
-  suspend fun deleteHouseholdById(id: String)
+  fun deleteHouseholdById(id: String, function: (String) -> Unit = {})
```
Comment (AleMerRom) [inline app/src/main/java/com/android/shelfLife/model/household/HouseHoldRepository.kt]: small criticism, you should change the name of the parameter  to onSuccess

File: app/src/main/java/com/android/shelfLife/model/household/HouseHoldRepositoryFirestore.kt [hunk 4]
```diff
@@ -224,31 +232,59 @@ constructor(
...
+    val originalStinkyPoints = _selectedHousehold.value?.stinkyPoints
+
+    // Optimistically update local cache
+    _selectedHousehold.value = _selectedHousehold.value?.copy(stinkyPoints = stinkyPoints)
+
+    // Perform Firebase operation
+    db.collection(collectionPath)
+        .document(householdId)
+        .update("stinkyPoints", stinkyPoints)
+        .addOnSuccessListener {
```
Comment (AleMerRom) [inline app/src/main/java/com/android/shelfLife/model/household/HouseHoldRepositoryFirestore.kt:252]: as previous this addOnSuccessListener is not necessary. You could remove it. It does not really do anything so it is not a big deal

File: app/src/main/java/com/android/shelfLife/model/foodFacts/FoodFactsRepository.kt [hunk 5]
```diff
@@ -22,6 +22,8 @@ interface FoodFactsRepository {
 
   fun resetSearchStatus()
 
+  fun setFailureStatus()
```
Comment (AleMerRom) [inline app/src/main/java/com/android/shelfLife/model/foodFacts/FoodFactsRepository.kt:25]: I like that you have added this function

File: app/src/main/java/com/android/shelfLife/model/recipe/RecipeRepository.kt [hunk 6]
```diff
@@ -38,21 +38,21 @@ interface RecipeRepository {
...
-  suspend fun updateRecipe(recipe: Recipe)
+  fun updateRecipe(recipe: Recipe)
 
   /**
    * Deletes a recipe from the repository and Firestore by its unique ID.
    *
    * @param recipeId The unique ID of the recipe to delete.
    */
-  suspend fun deleteRecipe(recipeId: String): Boolean
+  fun deleteRecipe(recipeId: String, deleteUID: (String) -> Unit = {})
```
Comment (AleMerRom) [inline app/src/main/java/com/android/shelfLife/model/recipe/RecipeRepository.kt:55]: in this case, the parameter deleteUID is not bad.

File: app/src/main/java/com/android/shelfLife/model/user/UserRepositoryFirestore.kt [hunk 7]
```diff
@@ -229,70 +240,91 @@ constructor(
           else -> currentUserData
         }
     _user.value = updatedUserData
-    userCollection.document(currentUser.uid).update(fieldName, updateValue)
+
+    // Perform Firebase operation
+    userCollection
+        .document(currentUser.uid)
+        .update(fieldName, updateValue)
+        .addOnSuccessListener {
```
Comment (AleMerRom) [inline app/src/main/java/com/android/shelfLife/model/user/UserRepositoryFirestore.kt:248]: this is redundant (check other comments for more info)

File: app/src/main/java/com/android/shelfLife/model/user/UserRepositoryFirestore.kt [hunk 8]
```diff
@@ -229,70 +240,91 @@ constructor(
...
+    // Optimistically update local cache
+    val currentUser = _user.value
+    val updatedHouseholdUIDs = currentUser?.householdUIDs?.plus(householdUID).orEmpty()
+    _user.value = currentUser?.copy(householdUIDs = updatedHouseholdUIDs)
+
+    // Perform Firebase operation
+    db.collection("users")
+        .document(userUID)
+        .update("householdUIDs", FieldValue.arrayUnion(householdUID))
+        .addOnSuccessListener {
```
Comment (AleMerRom) [inline app/src/main/java/com/android/shelfLife/model/user/UserRepositoryFirestore.kt:319]: another redundancy (check other comments for more info)

File: app/src/main/java/com/android/shelfLife/viewmodel/recipes/ExecuteRecipeViewModel.kt [hunk 9]
```diff
@@ -132,6 +135,21 @@ constructor(
   fun consumeSelectedItems() {
     if (householdUid != null) {
       foodItemsRepository.setFoodItems(householdId = householdUid, _availableFoodItems.value)
+      selectedFoodItemsForIngredients.value.values.forEach{ foodItems ->
```
Comment (AleMerRom) [inline app/src/main/java/com/android/shelfLife/viewmodel/recipes/ExecuteRecipeViewModel.kt]: I like the logic for the giving ratPoints

File: app/src/test/java/com/android/shelflife/viewmodel/utils/DeletionConfirmationViewModelTest.kt [hunk 10]
```diff
@@ -0,0 +1,301 @@
...
+                argThat { this.uid == "h2" && !this.members.contains("currentUserUID") }, any())
+        verify(userRepository).deleteHouseholdUID("h2")
+
+        // The selected household (h1) should remain unchanged
+        verify(houseHoldRepository, never()).selectHousehold(any())
+        verify(userRepository, never()).selectHousehold(any())
+        verify(foodItemRepository, never()).getFoodItems(any())
+      }
+
+  /*
```
Comment (AleMerRom) [inline app/src/test/java/com/android/shelflife/viewmodel/utils/DeletionConfirmationViewModelTest.kt]: you have this fully commented out test. Please delete it if it no longer needed

File: app/src/main/java/com/android/shelfLife/viewmodel/recipes/ExecuteRecipeViewModel.kt [hunk 11]
```diff
@@ -132,6 +135,22 @@ constructor(
   fun consumeSelectedItems() {
     if (householdUid != null) {
       foodItemsRepository.setFoodItems(householdId = householdUid, _availableFoodItems.value)
+      selectedFoodItemsForIngredients.value.values.forEach { foodItems ->
```
Comment (AleMerRom) [inline app/src/main/java/com/android/shelfLife/viewmodel/recipes/ExecuteRecipeViewModel.kt:138]: I like this logic . Good job

**Review by AleMerRom — CHANGES_REQUESTED** [review]
In this PR, you have done quite a few tasks 

In really like the making asynchronous. It looks really nice

i was testing the app and there where some issues with the deleting household. You already know about it, as you were next to me

there is also some names of parameters that you should change. And there is also a fully commented out text that you also need to change.

**Review by AleMerRom — APPROVED** [review]
good job. 

It all works nicely
