### PR TITLE
Fix android test repository and viewModel issue

### LINKED ISSUE #315: Fix android tests component instantiation
- We are unable to write android tests with viewModels and repositories for the moment

### PR DESCRIPTION
**Pull request by ElMaestroZ**
This pull request includes several changes to the test setup and implementation in the `OverviewTest` class, as well as some minor dependency adjustments. The high amount of lines changed is in part due to ktfmt format, please run this everytime you push!!!

### Test Refactoring:

* [`app/src/androidTest/java/com/android/shelfLife/ui/overview/OverviewTest.kt`](diffhunk://#diff-b47a8180c16e365e93f9e349273c5c7bac39748226df29ffbcf225c15d37d0baL1-R71): Refactored the `OverviewTest` class to use dependency injection with Dagger Hilt, replacing the manual mocking of repositories and view models. This change includes adding the `@HiltAndroidTest` annotation, injecting repositories, and setting up state flows for test data. [[1]](diffhunk://#diff-b47a8180c16e365e93f9e349273c5c7bac39748226df29ffbcf225c15d37d0baL1-R71) [[2]](diffhunk://#diff-b47a8180c16e365e93f9e349273c5c7bac39748226df29ffbcf225c15d37d0baL75-R102) [[3]](diffhunk://#diff-b47a8180c16e365e93f9e349273c5c7bac39748226df29ffbcf225c15d37d0baL114-R125) [[4]](diffhunk://#diff-b47a8180c16e365e93f9e349273c5c7bac39748226df29ffbcf225c15d37d0baL143-R151) [[5]](diffhunk://#diff-b47a8180c16e365e93f9e349273c5c7bac39748226df29ffbcf225c15d37d0baL172-R176) [[6]](diffhunk://#diff-b47a8180c16e365e93f9e349273c5c7bac39748226df29ffbcf225c15d37d0baL202-R201) [[7]](diffhunk://#diff-b47a8180c16e365e93f9e349273c5c7bac39748226df29ffbcf225c15d37d0baL221-R210) [[8]](diffhunk://#diff-b47a8180c16e365e93f9e349273c5c7bac39748226df29ffbcf225c15d37d0baL250-R249) [[9]](diffhunk://#diff-b47a8180c16e365e93f9e349273c5c7bac39748226df29ffbcf225c15d37d0baL306-R271) [[10]](diffhunk://#diff-b47a8180c16e365e93f9e349273c5c7bac39748226df29ffbcf225c15d37d0baL352-R282) [[11]](diffhunk://#diff-b47a8180c16e365e93f9e349273c5c7bac39748226df29ffbcf225c15d37d0baL378-R308) [[12]](diffhunk://#diff-b47a8180c16e365e93f9e349273c5c7bac39748226df29ffbcf225c15d37d0baL400-R322) [[13]](diffhunk://#diff-b47a8180c16e365e93f9e349273c5c7bac39748226df29ffbcf225c15d37d0baL432-R352)

### Dependency Updates:

* [`app/build.gradle.kts`](diffhunk://#diff-8cff73265af19c059547b76aca8882cbaa3209291406f52df1dafbbc78e80c46R271): Added `debugImplementation` for `libs.test.core.ktx` to ensure the test core library is available during debug builds.

### Import Cleanup:

* [`app/src/androidTest/java/com/android/shelfLife/ui/camera/PermissionDeniedScreenTest.kt`](diffhunk://#diff-3711cf35f5cca8fafdd759ae926033bc115ca51a0e07965cb6b269b2850cac95L6): Removed unused imports to clean up the codebase. [[1]](diffhunk://#diff-3711cf35f5cca8fafdd759ae926033bc115ca51a0e07965cb6b269b2850cac95L6) [[2]](diffhunk://#diff-3711cf35f5cca8fafdd759ae926033bc115ca51a0e07965cb6b269b2850cac95L17)

These changes streamline the test setup process, improve maintainability, and ensure that the tests are properly isolated and injected with the necessary dependencies.

### CODE REVIEW

File: app/src/main/java/com/android/shelfLife/viewmodel/overview/OverviewScreenViewModel.kt [hunk 1]
```diff
@@ -120,7 +118,9 @@ constructor(
       viewModelScope.launch {
         listFoodItemsRepository.foodItems.collect { foodItems ->
           foodItems.forEach { foodItem ->
-            if (foodItem.expiryDate!! < Timestamp.now() && foodItem.status != FoodStatus.EXPIRED) {
+            if (foodItem.expiryDate != null &&
```
Comment (alextheprophecy) [inline app/src/main/java/com/android/shelfLife/viewmodel/overview/OverviewScreenViewModel.kt:121]: # Good practice, but necessary?
good addition of the null check. I think however that its unnecessary since expiryDate is ALWAYS defined for fooditems.

File: app/src/main/java/com/android/shelfLife/ui/overview/Overview.kt [hunk 2]
```diff
@@ -37,8 +37,10 @@ import kotlinx.coroutines.launch
  * @param navigationActions The actions to handle navigation
  */
 @Composable
-fun OverviewScreen(navigationActions: NavigationActions) {
-  val overviewScreenViewModel = hiltViewModel<OverviewScreenViewModel>()
+fun OverviewScreen(
```
Comment (alextheprophecy) [inline app/src/main/java/com/android/shelfLife/ui/overview/Overview.kt:40]: ## Nice work refactoring
- As discussed in our stand up meetings, we agreed to have the hiltViewModels be (default initialised) parameters to the Screens, so that in the testing we can pass some test viewModels; good job applying this to the OverviewScreen you tested

File: app/src/main/java/com/android/shelfLife/ui/overview/FoodDisplayComponents.kt [hunk 3]
```diff
@@ -134,7 +134,7 @@ fun FoodItemCard(
       when (foodItem.foodFacts.quantity.unit) {
         FoodUnit.GRAM -> "g"
         FoodUnit.ML -> "ml"
-        FoodUnit.COUNT -> "in stock"
+        FoodUnit.COUNT -> " in stock"
```
Comment (alextheprophecy) [inline app/src/main/java/com/android/shelfLife/ui/overview/FoodDisplayComponents.kt:137]: ## Good fix
There was a padding issue between the count and the text. Maybe this should be part of a UI fix/refactor issue, but I see no problem with it being corrected in this PR since you are refactoring many little things

File: app/src/androidTest/java/com/android/shelfLife/ui/overview/OverviewTest.kt [hunk 4]
```diff
@@ -1,65 +1,74 @@
...
-  @get:Rule val composeTestRule = createComposeRule()
+  @Inject lateinit var houseHoldRepository: HouseHoldRepository
+  @Inject lateinit var listFoodItemsRepository: FoodItemRepository
+  @Inject lateinit var userRepository: UserRepository
+
+  private lateinit var overviewScreenViewModel: OverviewScreenViewModel
+
+  // This section might need to be moved to it's own file
+  private val selectedHousehold = MutableStateFlow<HouseHold?>(null)
+  private val householdToEdit = MutableStateFlow<HouseHold?>(null)
```
Comment (alextheprophecy) [inline app/src/androidTest/java/com/android/shelfLife/ui/overview/OverviewTest.kt:50]: ### Nit picky
- Since you removed the clickEditInDrawerLaunchesEditSelection()  test, I wonder how relevant the edithousehold stateflow is now; it is not used or initilaised in the test file. 
- Maybe add back a test flow for editing a household **(you removed the one from lines 317 to 331)**

File: app/src/androidTest/java/com/android/shelfLife/ui/overview/OverviewTest.kt
Comment (alextheprophecy) [inline app/src/androidTest/java/com/android/shelfLife/ui/overview/OverviewTest.kt:1]: ### Nit picky change:
- would it not be better to change the (previous) `onNodeWithText("Error").assertIsDisplayed()` for the errors with the relevant String.xml string? so like: `onNodeWithText(R.string.no_food_available).assertIsDisplayed()`  instead. So that if some strings were to get modified, the tests would still work automatically

> Excellent test template for Android tests btw:
> - good template, the entire team should now **focus** on delivering quality tests of the same format

**Review by alextheprophecy — APPROVED** [review]
## Overall great job!
- Amazing job Robin, we now have a really good android test template using hte Hilt injections. You correctly applied what we agreed on during our meetings

## Nit picky changes
- I mentioned a few potential changes, but they really aren't important, especially at this stage of the project.
- I see however that we are missing some di/modules for the Recipe repository, and maybe some others. These should be added in the upcoming tasks.

## Conclusion
- The line coverage is COMPLETELY fine. The ktfmt formatting was never run it seems... so the modified lines is **absolutely** not a clear representation of your changes. 
- The OverviewTest is a great template for our next tests.
