### PR TITLE
Fix/335 fix food facts quantity

### LINKED ISSUE #335: Fix Food Facts Quantity
- Fix the parsing of quantity and units from the food facts api

### PR DESCRIPTION
**Pull request by alextheprophecy**
# PR: Fix FoodFacts quantities

## Issue fixed
(previous issue): Scanned food items were  **always** being scanned and saved with a default **1g**

### Updated the `OpenFoodFactsRepository`
  - Now properly parses "ml", "g", "cl", "ml, "dl", "kg" correctly into the right `Quantity` data object (using regex)
  - Now Defaults to 1 count, which makes more sense than 1 gram

### Updated the `FoodDisplayComponent` and `IndividualFoodItem` Screens
  - Now properly show the Quantity
  - Now have proper unit switching (ml -> L etc.)

### CODE REVIEW

File: app/src/main/java/com/android/shelfLife/model/foodFacts/FoodFacts.kt [hunk 1]
```diff
@@ -41,7 +41,32 @@ data class Quantity(
     val unit: FoodUnit = FoodUnit.GRAM // Unit of the quantity
 ) {
   override fun toString(): String {
-    return "$amount ${unit.name.lowercase()}"
+    return when (unit) {
```
Comment (AleMerRom) [inline app/src/main/java/com/android/shelfLife/model/foodFacts/FoodFacts.kt:44]: this is makes the UX much nicer.

File: app/src/main/java/com/android/shelfLife/model/foodFacts/OpenFoodFactsRepository.kt [hunk 2]
```diff
@@ -26,7 +26,7 @@ class OpenFoodFactsRepository(
 ) : FoodFactsRepository {
 
   companion object {
-    private val MAX_RESULTS = 7 // Adjust the number of results as needed
+    private const val MAX_RESULTS = 7 // Adjust the number of results as needed
```
Comment (AleMerRom) [inline app/src/main/java/com/android/shelfLife/model/foodFacts/OpenFoodFactsRepository.kt:29]: nice that you use a const

File: app/src/main/java/com/android/shelfLife/model/foodFacts/OpenFoodFactsRepository.kt [hunk 3]
```diff
@@ -189,4 +192,46 @@ class OpenFoodFactsRepository(
         nutritionFacts = nutritionFacts,
         imageUrl = imageUrl)
   }
+
+  fun parseOpenFoodFactsQuantity(quantityString: String): Quantity {
```
Comment (AleMerRom) [inline app/src/main/java/com/android/shelfLife/model/foodFacts/OpenFoodFactsRepository.kt:196]: I really like this code

**Review by AleMerRom — APPROVED** [review]
Really really good job. I really like your code, you have also added nice comments. 

Good job
